Possible improvements
alex-konn/local-graylog pull request #1
Opened 2019-10-28 09:48 UTC by linuspahl

Hey Alex, ich habe mal die Readme's um meine learnings erweitert.

Da ich filebeat so unter OSX nicht nuten konnte, habe ich die Konfiguration um die Möglichkeit ergänzt jede beliebige Log Datei an Graylog zu senden. Mit ein paar Beispielen, wie man random logs generiert.

2019-10-28 10:09 UTC, alex-konn requested changes
Danke, Linus! Das sieht doch alles sehr cool aus. Ich hätte einen einzigen Änderungswunsch: Bitte trenn' doch die random-logs-Geschichte von docker logs. Ich finde das Feature an sich cool, würde das aber separat halten und mit zwei getrennten filebeats-containern anbfrühstücken. das heißt, es gäbe docker-logs/ und random-logs/ statt docker-logs/random-logs. 
Das macht es erstens klarer, dass das zwei verschiedene Sachen sind und zweitens kannste dann auch verschiedene Inputs dafür nehmen und die Messages leichter unterschiedlich anreichern.
Ergibt das SInn für dich?

2019-10-28 10:27 UTC, linuspahl commented
Das hört sich gut an, das mache ich so!

2019-11-08 15:52 UTC, alex-konn commented on random-logs/filebeat.yml
> +ssl.verification_mode: none
Does this not conflict with the logging settings in the other filebeats container? I.e. wouldn't they overwrite each others' logs?

2019-11-08 16:40 UTC, alex-konn approved these changes

2019-11-08 16:40 UTC, merged